audio_tone_levels:
  name: Adjust Audio Tone Levels
  description: Adjust the Bass and Treble values for SoundTouch devices that support it.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device whose audio tone levels will be adjusted.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    bass_level:
      name: Bass Level
      description: The bass level to set.
      example: 50
      required: true
      selector:
        number:
          min: -100
          max: 100
          step: 25
          mode: slider
    treble_level:
      name: Treble Level
      description: The treble level to set.
      example: 50
      required: true
      selector:
        number:
          min: -100
          max: 100
          step: 25
          mode: slider

play_contentitem:
  name: Play Content Item
  description: Play media content from a content item source (e.g. TUNEIN station, etc) on a SoundTouch device.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device to play the media.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    name:
      name: Content Item Name
      description: Name of the content item.
      example: "K-LOVE Radio"
      required: false
      selector:
        text:
    source:
      name: Source
      description: Source to select to play the content; the value is case-sensitive, and should normally be UPPER case.
      example: "TUNEIN"
      required: true
      selector:
        text:
    source_account:
      name: Source Account
      description: Source account this content item is played with.  Default is none.
      example: ""
      required: false
      selector:
        text:
    item_type:
      name: Item Type
      description: Type of content item to play; the value is case-sensitive, and should normally be lower case.
      example: "stationurl"
      required: false
      selector:
        text:
    location:
      name: Content Location
      description: A direct link to the media content that will be played.
      example: "/v1/playback/station/s33828"
      required: false
      selector:
        text:
    container_art:
      name: Container Art
      description: A direct link to the container art (if present).
      example: "http://cdn-profiles.tunein.com/s33828/images/logog.png?t=637986894890000000"
      required: false
      selector:
        text:
    is_presetable:
      name: Is Presetable?
      description: true if this item can be saved as a Preset; otherwise, false.
      example: "false"
      required: true
      selector:
        boolean:

play_handoff:
  name: Play Handoff
  description: Handoff playing source from one SoundTouch device to another.
  fields:
    entity_id_from:
      name: From Entity ID
      description: Entity ID of the SoundTouch device that is currently playing.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    entity_id_to:
      name: To Entity ID
      description: Entity ID of the SoundTouch device that needs to play what the 'from' device is currently playing.
      example: "media_player.soundtouch_bedroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    restore_volume:
      name: Restore Volume?
      description: True to handoff the FROM device volume level to the TO device; False (default) to leave the TO device volume level as-is.
      example: "true"
      required: true
      selector:
        boolean:
    snapshot_only:
      name: Snapshot Only?
      description: True to only handoff the snapshot and not trigger the restore and power off; False (default) to handoff the snapshot, restore it, and power off the FROM device.
      example: "true"
      required: true
      selector:
        boolean:

play_tts:
  name: Play TTS Message
  description: Play Text-To-Speech notification on a SoundTouch device.  Note that this is limited to ST10,20,30 devices, as Bose ST300 does not support notifications (AFAIK).
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device to play the message.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    message:
      name: Message Text
      description: The message that will be converted from text to speech and played on the device.
      example: "Hello World"
      required: true
      selector:
        text:
    artist:
      name: Artist Status Text
      description: The message text that will appear in the NowPlaying Artist node; if omitted, default is "TTS Notification".
      example: "TTS Notification"
      required: false
      selector:
        text:
    album:
      name: Album Status Text
      description: The message text that will appear in the NowPlaying Album node; if omitted, default is "Google TTS".
      example: "Google TTS"
      required: false
      selector:
        text:
    track:
      name: Track Status Text
      description: The message text that will appear in the NowPlaying Track node; if omitted, default is the message value.
      example: "Hello World"
      required: false
      selector:
        text:
    tts_url:
      name: TTS Service Url
      description: The Text-To-Speech url used to translate the message.  The value should contain a "{saytext}" format parameter, that will be used to insert the encoded message text.
      example: "http://translate.google.com/translate_tts?ie=UTF-8&tl=EN&client=tw-ob&q={saytext}"
      required: false
      selector:
        text:
    volume_level:
      name: Volume Level
      description: The temporary volume level that will be used when the message is played.  Specify a value of zero to play at the current volume.  Default is zero.
      example: 50
      required: false
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    app_key:
      name: Bose App Key
      description: Bose Developer API application key; if omitted, defaults to a pre-defined App Developer Key.
      example: "abcdefghijklmnopqrstuvwxyz"
      required: false
      selector:
        text:

play_url:
  name: Play URL Media
  description: Play media content from a URL on a SoundTouch device.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device to play the media.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    url:
      name: URL
      description: The url to play; value must start with http or https.
      example: "https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_1MB_MP3.mp3"
      required: true
      selector:
        text:
    artist:
      name: Artist Status Text
      description: The message text that will appear in the NowPlaying Artist node; if omitted, default is "Unknown Artist".
      example: "FreeTestData.com"
      required: false
      selector:
        text:
    album:
      name: Album Status Text
      description: The message text that will appear in the NowPlaying Album node; if omitted, default is "Unknown Album".
      example: "MP3 Test Data"
      required: false
      selector:
        text:
    track:
      name: Track Status Text
      description: The message text that will appear in the NowPlaying Track node; if omitted, default is "Unknown Track".
      example: "Free_Test_Data_1MB_MP3"
      required: false
      selector:
        text:
    volume_level:
      name: Volume Level
      description: The temporary volume level that will be used when the media is played.  Specify a value of zero to play at the current volume.  Default is zero.
      example: 50
      required: false
      selector:
        number:
          min: 0
          max: 100
          step: 5
          unit_of_measurement: "%"
          mode: slider
    app_key:
      name: Bose App Key
      description: Bose Developer API application key; if omitted, defaults to a pre-defined App Developer Key.
      example: "abcdefghijklmnopqrstuvwxyz"
      required: false
      selector:
        text:
    get_metadata_from_url_file:
      name: Get Metadata From URL?
      description: If true, the artist, album, and song title metadata details will be retrieved from the ID3 header of the url content (if available); otherwise, False to use the artist, album, and song title arguments specified.
      example: "false"
      required: false
      selector:
        boolean:

preset_list:
  name: Get Preset List
  description: Retrieves the list of presets defined to the device.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device whose preset list will be retrieved.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player

recent_list:
  name: Get Recent List
  description: Retrieves the list of recently played items defined to the device.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device whose recently played list will be retrieved.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player

remote_keypress:
  name: Remote Keypress
  description: Simulates the press and release of a key on the SoundTouch device remote control.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device to be controlled.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    key_id:
      name: Key ID
      description: SoundTouch remote control key identifier. 
        Note that some keys on the SoundTouch remote control are not sent to the SoundTouch device, 
        and therefore are not supported by this service.
      example: "AUX_INPUT"
      required: true
      selector:
        select:
          mode: dropdown
          sort: true
          options:
            - PLAY
            - PAUSE
            - PLAY_PAUSE
            - STOP
            - PREV_TRACK
            - NEXT_TRACK
            - THUMBS_UP
            - THUMBS_DOWN
            - BOOKMARK
            - POWER
            - MUTE
            - VOLUME_UP
            - VOLUME_DOWN
            - PRESET_1
            - PRESET_2
            - PRESET_3
            - PRESET_4
            - PRESET_5
            - PRESET_6
            - AUX_INPUT
            - SHUFFLE_OFF
            - SHUFFLE_ON
            - REPEAT_OFF
            - REPEAT_ONE
            - REPEAT_ALL
            - ADD_FAVORITE
            - REMOVE_FAVORITE

snapshot_restore:
  name: Snapshot Restore
  description: Restore SoundTouch device settings from a snapshot.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device whose settings will be restored from a snapshot.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
    restore_volume:
      name: Restore Volume?
      description: Indicates if the volume also needs to be restored (True, default) or not (False).
      example: "false"
      required: true
      selector:
        boolean:

snapshot_store:
  name: Snapshot Store
  description: Store SoundTouch device settings to a snapshot.
  fields:
    entity_id:
      name: Entity ID
      description: Entity ID of the SoundTouch device whose settings will be stored to a snapshot.
      example: "media_player.soundtouch_livingroom"
      required: true
      selector:
        entity:
          integration: soundtouchplus
          domain: media_player
